-----BEGIN PRIVATE KEY-----
MIGTAgEAMBsdfsMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMCsG1HjBmh9UwIvA
2mwzWbeCdfLNdBvTkfeJkmNVDjz8CgCgYIKoZIzj0DAQehRANCAASQb0Ef0cwyC3te
hhtRSZkbHnOFupdsfsfYYaV1XAeU//KB9XzANCjc2szkmyx+MD0nn4TRqhOQp5B7OUQt6
R1iqSMbO
-----END PRIVATE KEY-----